@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ContactBookParser" as ContactBookParser LOGIC_COLOR
participant ":FilterCommandParser" as FilterCommandParser LOGIC_COLOR
participant "command:FilterCommand" as FilterCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

skinparam boxPadding 10

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("filter t/friends")
activate LogicManager

LogicManager -> ContactBookParser : parseCommand("filter t/friends")
activate ContactBookParser

create FilterCommandParser
ContactBookParser -> FilterCommandParser
activate FilterCommandParser

FilterCommandParser --> ContactBookParser
deactivate FilterCommandParser

ContactBookParser -> FilterCommandParser : parse("t/friends")
activate FilterCommandParser

create FilterCommand
FilterCommandParser -> FilterCommand
activate FilterCommand

FilterCommand --> FilterCommandParser : command
deactivate FilterCommand

FilterCommandParser --> ContactBookParser : command
deactivate FilterCommandParser

FilterCommandParser -[hidden]-> ContactBookParser
destroy FilterCommandParser

ContactBookParser --> LogicManager : command
deactivate ContactBookParser

LogicManager -> FilterCommand : execute()
activate FilterCommand

FilterCommand -> Model : updateFilteredPersonList(predicate)
activate Model

Model --> FilterCommand
deactivate Model

create CommandResult
FilterCommand -> CommandResult
activate CommandResult

CommandResult --> FilterCommand
deactivate CommandResult

FilterCommand --> LogicManager : commandResult
deactivate FilterCommand

[<--LogicManager
deactivate LogicManager
@enduml
